version: '3'
services:
  base-production:
    container_name: 'xta_membership_fe'
    image: 'huynhdn/xta_membership_fe:1.0'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - common

networks:
  common:
    driver: bridge
